### ISSUE TITLE
panic in version 3.14

### ISSUE THREAD

**Issue by das-at-github** [GESkunkworks/gossamer3#253]
## Disclaimer

This is a public issue. Please do not include any information that is company-specific in your issue. Redact all sensitive information in accordance with your company's policies to ensure you are not leaking any company sensitive information. This includes company identity provider URLs.

## Actual Behavior
$ file gossamer3
gossamer3: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=uAK0ixsO-FNdToxFvzoQ/beiVAKSN4cS1xtbHAopu/e1xulXVQdnS2xkj13ZN9/YE5-RsIHgnhcrgmdNuop, not stripped

$ gossamer3
panic: runtime error: slice bounds out of range [308:282]

goroutine 1 [running]:
github.com/aulanov/go%2edbus.sessionBusPlatform(0xb99d97, 0x18, 0x0)
        /Users/runner/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn_other.go:26 +0x1e7
github.com/aulanov/go%2edbus.SessionBusPrivate(0xd0, 0xb31060, 0xfd5cef627dd4e401)
        /Users/runner/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:99 +0xa7
github.com/aulanov/go%2edbus.SessionBus(0x0, 0x0, 0x0)
        /Users/runner/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:76 +0xb5
github.com/99designs/keyring.init.1()
        /Users/runner/go/pkg/mod/github.com/99designs/keyring@v0.0.0-20190110203331-82da6802f65f/kwallet.go:18 +0x26

## Steps to Reproduce the Problem

1. simply running gossamer3 with or without options

## Specifications
Manufacturer :HP
Model :HP ZBook 17 G3
Linux xxxxxxxxxx   4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

  - Version:
  - Platform:
  - Subsystem:   WSL - Ubuntu

**Comment by Squwid** [comment]
Are you still having this issue? For WSL try to still use the amd64 windows executable rather than the linux one
