### ISSUE TITLE
Unable o get the ARM based packages in releases list

### ISSUE THREAD

**Issue by 503125606** [GESkunkworks/gossamer3#323]
Unable o get the ARM based packages in releases list

when we execute these commands it required to have package in releases to get.

ARM based package not available in releases.

$ CURRENT_VERSION=3.1.3
$ wget https://github.com/GESkunkworks/gossamer3/releases/download/v${CURRENT_VERSION}/gossamer3_${CURRENT_VERSION}_linux_amd64.tar.gz
$ tar -xzvf gossamer3_${CURRENT_VERSION}_linux_amd64.tar.gz -C ~/.local/bin
$ chmod u+x ~/.local/bin/gossamer3

**Comment by Squwid** [comment]
Fixed in the most recent release! arm64 based linux binary is available here - https://github.com/GESkunkworks/gossamer3/releases/latest
