### ISSUE TITLE
Not able to login through gossamer3 

### ISSUE THREAD

**Issue by AshokPokhriyalGE** [GESkunkworks/gossamer3#59]
Not able to login through gossamer3 , gives "authentication failed" message
on each attempt my SSO login password get locked and i need to reset it with new password.

**Comment by AshokPokhriyalGE** [comment]
now iam able to connect,

**Comment by Squwid** [comment]
Make sure that you are using the latest 3.1.3 version that has better support for wrong username + password combinations
