### ISSUE TITLE
Very high memory usage during bulk-login

### ISSUE THREAD

**Issue by dparkes** [GESkunkworks/gossamer3#76]
Hi Mike

Bulk login seems use all available memory on my Mac when its running (I have 8GB, but the process uses up to 12GB). CPU also spikes to 3-400% across all 4 cores but kernel_task is high as well (my guess is kernel_task is performing memory compression/paging out related stuff but i don't know how to prove that).

At the moment i've configured gossamer with a large timeout just as a workaround so it can finish.

I'll email you with my config. I can't post here as its a potential security issue.

Thanks,
David

% gossamer3 --version
3.1.3

% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15

top (with some lines removed):
Processes: 294 total, 10 running, 284 sleeping, 1851 threads           18:49:36
Load Avg: 5.18, 3.24, 2.54  CPU usage: 29.72% user, 55.52% sys, 14.74% idle
MemRegions: 88041 total, 1745M resident, 84M private, 1418M shared.
PhysMem: 8172M used (1992M wired), 18M unused.
VM: 1487G vsize, 1992M framework vsize, 26645346(59341) swapins, 28156246(27372)

PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP
76121  gossamer3    342.5 01:16.88 18/8   1    61    8284M+ 0B     5889M+ 76121
0      kernel_task  194.3 29:17.39 209/12 0    0     512M+  0B     0B     0
69945  iTerm2       28.1  00:38.01 10     7    396   111M+  4096B- 52M-   69945

**Comment by MichaelPalmer1** [comment]
closed by #87
