### ISSUE TITLE
"panic: runtime error: slice bounds out of range"

### ISSUE THREAD

**Issue by z0ned42** [GESkunkworks/gossamer3#89]
## Disclaimer

This is a public issue. Please do not include any information that is company-specific in your issue. Redact all sensitive information in accordance with your company's policies to ensure you are not leaking any company sensitive information. This includes company identity provider URLs.

## Expected Behavior

Expected to be able to run, does not

## Actual Behavior
This is what happens when I run "gossamer3" or "gossamer3 configure":

"panic: runtime error: slice bounds out of range [308:282]
goroutine 1 [running]:
[Github errors that I'm not sure if I should post (Keyring.init is the last one)]
"
## Steps to Reproduce the Problem

  1. Deleted gossamer, redownloaded and extracted it, same issue
  2. gpg key has been made and everything else works. 
 

## Specifications

  - Version: gossamer 3.1.3
  - Platform: Windows
  - Subsystem: WSL version 1 (Ubuntu 20.04)

**Comment by Squwid** [comment]
Since Keyring is not available on WSL, running the Linux gossamer3 binary won't work. However, the windows binary should work just fine on WSL.
